<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>10_catch捕获异常</title>
</head>

<body>
    <p>123</p>
    <script>
        function fn() {
            try {
                // 将可能出错的代码编写在 try...catch 的 try块中
                const p = document.querySelector('.p');
                p.style.color = 'red';
            } catch (error) {
                // throw new Error("")
                // console.error(error.message);
                //使用 throw 拦截是错误，并输出到控制台。默认 throw 不中断程序
                throw new Error(error.message);
                // 使用 return 中断程序
                return;
            }
            finally {
                // 无论程序执行对错，都会执行 finally语句
                alert('弹出对话窗口');
            }
            console.log(111);
        }
        fn()
    </script>
</body>

</html>